import { GameColors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const PLAYER_COUNTER_COLOR = GameColors.playerBlue;
export const ENEMY_COUNTER_COLOR = GameColors.red;

export const styles = StyleSheet.create({
  battleContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    paddingHorizontal: 32,
  },
  fieldSection: {
    gap: 16,
    alignItems: 'center',
  },
  gridWrapper: {
    alignSelf: 'center',
  },
  glowBorder: {
    borderWidth: 2,
    borderRadius: 4,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  dividerLine: {
    flex: 1,
    height: 1,
  },
  dividerTextContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  dividerText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 3,
  },
  verdictText: {
    position: 'absolute',
    fontFamily: 'BlackOpsOne',
    fontSize: 13,
  },
  counterWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shipIconPlayer: {
    width: 0,
    height: 0,
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderLeftWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: PLAYER_COUNTER_COLOR,
  },
  shipIconEnemy: {
    width: 0,
    height: 0,
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderRightWidth: 6,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderRightColor: ENEMY_COUNTER_COLOR,
  },
  counterTextContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterText: {
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 3,
  },
  counterFlashText: {
    position: 'absolute',
  },
  sunkLabel: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 10,
    top: '40%',
  },
  sunkLabelText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 22,
    letterSpacing: 3,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  retreatButton: {
    position: 'absolute',
    bottom: 24,
    left: 24,
  },
  retreatButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: GameColors.blueBorder,
    borderRadius: 4,
  },
  retreatButtonPressed: {
    backgroundColor: GameColors.bluePressedBg,
  },
  retreatIcon: {
    fontSize: 10,
    color: GameColors.labelFaded,
  },
  retreatText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 11,
    letterSpacing: 3,
    color: GameColors.label,
  },
  confirmOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    backgroundColor: GameColors.confirmOverlayBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmDialog: {
    backgroundColor: GameColors.confirmDialogBg,
    borderWidth: 1,
    borderColor: GameColors.blueBorder,
    borderRadius: 6,
    paddingVertical: 28,
    paddingHorizontal: 32,
    alignItems: 'center',
    gap: 24,
    marginHorizontal: 32,
  },
  confirmMessage: {
    fontFamily: 'BlackOpsOne',
    fontSize: 14,
    letterSpacing: 1,
    color: GameColors.label,
    textAlign: 'center',
    lineHeight: 22,
  },
  confirmButtons: {
    flexDirection: 'row',
    gap: 16,
  },
  holdButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: GameColors.blueBorder,
    borderRadius: 4,
  },
  holdButtonPressed: {
    backgroundColor: GameColors.bluePressedBg,
  },
  holdButtonText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 11,
    letterSpacing: 2,
    color: GameColors.label,
  },
  confirmRetreatButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: GameColors.red,
    borderRadius: 4,
  },
  confirmRetreatButtonPressed: {
    backgroundColor: GameColors.retreatPressedBg,
  },
  confirmRetreatText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 11,
    letterSpacing: 2,
    color: GameColors.red,
  },
  retreatFlagWrapper: {
    position: 'absolute',
    top: -44,
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 15,
  },
  retreatFlagText: {
    fontSize: 28,
  },
  retreatDarkOverlay: {
    zIndex: 20,
    backgroundColor: GameColors.retreatOverlay,
  },
  retreatWordOverlay: {
    zIndex: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  retreatWordText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 48,
    letterSpacing: 4,
    color: GameColors.red,
    textShadowColor: 'rgba(0,0,0,0.9)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 12,
  },
  playerPulseOverlay: {
    backgroundColor: GameColors.playerPulse,
    borderRadius: 2,
  },
  defeatGridFlash: {
    backgroundColor: GameColors.red,
    borderRadius: 2,
  },
  victoryGridFlash: {
    backgroundColor: GameColors.fireGlow,
    borderRadius: 2,
  },
  victoryOverlay: {
    zIndex: 20,
    backgroundColor: GameColors.retreatOverlay,
  },
  victoryCalloutWrapper: {
    zIndex: 21,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  victoryText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 52,
    letterSpacing: 4,
    color: GameColors.gold,
    textShadowColor: GameColors.goldShadow,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  endgameSubtitle: {
    fontFamily: 'BlackOpsOne',
    fontSize: 14,
    letterSpacing: 2,
    color: GameColors.label,
  },
  endgameButtons: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 32,
  },
  playAgainButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderWidth: 2,
    borderColor: GameColors.fireGold,
    borderRadius: 4,
  },
  playAgainButtonPressed: {
    backgroundColor: GameColors.fireGoldBgPressed,
  },
  playAgainText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 13,
    letterSpacing: 2,
    color: GameColors.fireGold,
  },
  makePortButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: GameColors.blueBorder,
    borderRadius: 4,
  },
  makePortButtonPressed: {
    backgroundColor: GameColors.bluePressedBg,
  },
  makePortText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 13,
    letterSpacing: 2,
    color: GameColors.label,
  },
  devButtonsContainer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  devVictoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: GameColors.fireGold,
    borderRadius: 4,
  },
  devVictoryText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 11,
    letterSpacing: 3,
    color: GameColors.fireGold,
  },
  devDefeatButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: GameColors.red,
    borderRadius: 4,
  },
  devDefeatText: {
    fontFamily: 'BlackOpsOne',
    fontSize: 11,
    letterSpacing: 3,
    color: GameColors.red,
  },
});
